name: Build Flet APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install flet pandas openpyxl

      - name: Build APK
        run: |
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: swcc-app-release
          path: build/apk/*.apk
